### ISSUE TITLE
Please Specific All the version number of all the requirement  package.

### ISSUE THREAD

**Issue by 312shan** [samlobel/RaCT_CF#1]
can not run the code , with many error, can you Please Specific All the version number of all the requirement  package. so we can try to run your code.

**Comment by samlobel** [comment]
Hi, sorry to hear that. Could you be more specific about the error? It works from a fresh installation for me, provided I'm in python3 and using the proper version of tensorflow. I'm updating the readme to be more permissive about tensorflow versions (1.10 through 1.14 seem to work).
